"""create members table

Revision ID: 01e743878ad2
Revises: 
Create Date: 2026-07-03 13:55:03.984516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e743878ad2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('login_id', sa.String(length=12), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('student_id', sa.String(length=10), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=10), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('admin', 'pm', 'member', name='member_role'), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('github_username', sa.String(length=39), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('tech_stack', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members')),
    sa.UniqueConstraint('login_id', name=op.f('uq_members_login_id')),
    sa.UniqueConstraint('phone_number', name=op.f('uq_members_phone_number')),
    sa.UniqueConstraint('public_id', name=op.f('uq_members_public_id')),
    sa.UniqueConstraint('student_id', name=op.f('uq_members_student_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
