"""add email, make department and grade required

Revision ID: 3b2825688024
Revises: 01e743878ad2
Create Date: 2026-07-07 14:16:23.635794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b2825688024'
down_revision: Union[str, Sequence[str], None] = '01e743878ad2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=False))
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.create_unique_constraint(batch_op.f('uq_members_email'), ['email'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_members_email'), type_='unique')
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('department',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
